# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

# registries:
#   GHDR: # Github Docker Registry
#     type: docker-registry
#     url: ghcr.io
#     username: ${{ github.repository_owner }}
#     password: ${{ secrets.GITHUB_TOKEN }}

updates:
  - package-ecosystem: "pip" # See documentation for possible values
    schedule:
        interval: "weekly"
    directories:
      - "/*_requirements.txt"
      - "/shared_lib"
      - "/api"
      - "/worker"
  - package-ecosystem: "docker" # See documentation for possible values
    schedule:
        interval: "weekly"
    directories:
      - "/Dockerfile.*"
      - "/"
