networks:
  app-network:
    driver: bridge

# volumes:
#   pg_data_17:

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ${API_IMAGE_NAME:-color_api}
    mem_limit: 384M
    cpu_shares: 384
    profiles:
      - api
      - all
    environment:
      - MIN_LOG_LEVEL=${MIN_LOG_LEVEL:-info}

      - HOST=${API_HOST:-0.0.0.0}
      - PORT=${API_PORT:-8000}
      - API_DELAY_MIN=${API_DELAY_MIN:-0}
      - API_DELAY_MAX=${API_DELAY_MAX:-0}

      - REDIS_HOST=${REDIS_HOST:-mem_db}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      mem_db:
        condition: service_healthy
      sql_db:
        condition: service_started
    deploy:
      replicas: ${API_CLUSTER_SIZE:-1}
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: ${WORKER_IMAGE_NAME:-color_worker}
    mem_limit: 384M
    cpu_shares: 384
    profiles:
      - worker
      - all
    environment:
      - MIN_LOG_LEVEL=${MIN_LOG_LEVEL:-info}

      - HOST=${WORKER_HOST:-0.0.0.0}
      - PORT=${WORKER_PORT:-8000}
      - WORKER_DELAY_MIN=${WORKER_DELAY_MIN:-0}
      - WORKER_DELAY_MAX=${WORKER_DELAY_MAX:-0}

      - REDIS_HOST=${REDIS_HOST:-mem_db}
      - REDIS_PORT=${REDIS_PORT:-6379}

      - POSTGRES_HOST=${POSTGRES_HOST:-sql_db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-pguser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpwd}
      - POSTGRES_DB=${POSTGRES_DB:-dev}
    depends_on:
      mem_db:
        condition: service_started
      sql_db:
        condition: service_healthy
    deploy:
      replicas: ${WORKER_CLUSTER_SIZE:-1}
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  load_balancer:
    image: nginx:1-alpine
    mem_limit: 256M
    cpu_shares: 512
    profiles:
      - api
      - all
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${LOAD_BALANCER_PORT:-8000}:80"
    networks:
      - app-network
    deploy:
      replicas: ${LOAD_BALANCER_CLUSTER_SIZE:-1}
      restart_policy:
        condition: on-failure

  mem_db:
    image: redis:7-alpine
    mem_limit: 500M
    cpu_shares: 1024
    profiles:
      - db
      - all
    networks:
      - app-network
    ports:
      - 16379:6379
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: |
        redis-cli --raw incr ping
      interval: 5s
      timeout: 2s
      retries: 3
      # start_period: 1s

  sql_db:
    image: postgres:17-alpine
    mem_limit: 1G
    cpu_shares: 1024
    profiles:
      - db
      - all
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER:-pguser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpwd}
      - POSTGRES_DB=${POSTGRES_DB:-dev}
    networks:
      - app-network
    ports:
      - 15432:5432
    volumes:
      # NOTE: uncomment the line bellow to persist the data to virtual volume
      # - pg_data_17:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pguser} -d ${POSTGRES_DB:-dev}"]
      interval: 5s
      timeout: 15s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
