name: Container Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
          tags: ${{ github.repository }}/color_api:${{ github.ref_name }}
      - name: Build and push Worker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
          tags: ${{ github.repository }}/color_worker:${{ github.ref_name }}