name: Containers Build & Push

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/pylint.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/pylint.yml'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_SLUG: ''
      GHCR_IMAGE_ROOT: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}'
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: extract env vars
        run: |
          export BRANCH_SLUG=`echo ${BRANCH_NAME} | sed 's/[^a-zA-Z0-9_]/-/g' | sed -e 's/\(.*\)/\L\1/'`
          echo "${BRANCH_SLUG}" | grep -q 'main' && \
            (export BRANCH_SLUG='latest'; echo 'change branch slug to latest') || \
            else echo "keeping slug: ${BRANCH_SLUG}"
          echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV    
      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
          tags: ${{ env.GHCR_IMAGE_ROOT }}/color_api:${{ env.BRANCH_SLUG }}
          file: Dockerfile.api
          context: .
          platforms: linux/amd64,linux/arm64
      - name: Build and push Worker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
          tags: ${{ env.GHCR_IMAGE_ROOT }}/color_worker:${{ env.BRANCH_SLUG }}
          file: Dockerfile.worker
          context: .
          platforms: linux/amd64,linux/arm64