name: Pylint

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/container_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        cat shared_lib/requirements.txt > combined_requirements.txt
        echo '' >> combined_requirements.txt
        cat api/requirements.txt >> combined_requirements.txt
        echo '' >> combined_requirements.txt
        cat worker/requirements.txt >> combined_requirements.txt
        echo '' >> combined_requirements.txt
        cat ci_requirements.txt >> combined_requirements.txt
        echo '' >> combined_requirements.txt

        sort -u combined_requirements.txt > requirements.txt
        echo 'combined & unique requirement file:'
        cat requirements.txt
        echo ''
        
        echo 'installing requirements:'
        echo ''
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C0114,C0115,C0116,R0903,R0801 $(git ls-files '*.py')
    - name: Type check ./shared_lib with mypy
      run: |
        MYPYPATH=shared_lib mypy --config-file=./mypy.ini --install-types --fast-module-lookup \
          --ignore-missing-imports --show-column-numbers --namespace-packages \
          --explicit-package-bases ./shared_lib
    - name: Type check ./api with mypy
      run: |
        MYPYPATH=shared_lib mypy --config-file=./mypy.ini --install-types --fast-module-lookup \
          --ignore-missing-imports --show-column-numbers --namespace-packages \
          --explicit-package-bases ./api
    - name: Type check ./worker with mypy
      run: |
        MYPYPATH=shared_lib mypy --config-file=./mypy.ini --install-types --fast-module-lookup \
          --ignore-missing-imports --show-column-numbers --namespace-packages \
          --explicit-package-bases ./worker
        
